<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ACEFWUCreator</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Serilog">
      <HintPath>msi_work/files3/Serilog.dll</HintPath>
    </Reference>
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>msi_work/files3/ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>msi_work/files3/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../../../../usr/local/share/dotnet/shared/Microsoft.NETCore.App/10.0.12/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>