namespace ICUFWUCreator;

public enum ICUObjectTypes
{
	OBJECT_LOGO_CUSTOMER,
	OBJECT_LOGO_ACCEPTED,
	OBJECT_LOGO_CHARGING,
	OBJECT_LOGO_SOCKETERROR,
	OBJECT_LOGO_COMMUNICATING,
	OBJECT_ROBOTICA_REGULAR_28,
	OBJECT_ROBOTICA_REGULAR_29,
	OBJECT_LANGUAGE,
	OBJECT_ROBOTICA_REGULAR_30
}
