namespace ICUNetwork;

public enum EAHWPCPROStates
{
	CPRO_STATE_UNKNOWN,
	CPRO_STATE_INACTIVE,
	CPRO_STATE_CONNECTED_ISO15118_PWM,
	CPRO_STATE_WAIT_FOR_EV_CONNECT,
	CPRO_STATE_EV_CONNECTED,
	CPRO_STATE_ACTIVE,
	CPRO_STATE_WAIT_FOR_S2_CLOSE,
	CPRO_STATE_WAIT_FOR_S2_OPEN,
	CPRO_STATE_SUSPENDED,
	CPRO_STATE_VENTILATING,
	CPRO_STATE_WAKEUP_STATE_E,
	CPRO_STATE_WAKEUP_STATE_B1,
	CPRO_STATE_ERROR,
	CPRO_STATE_ERROR_EV_DETECT,
	CPRO_STATE_WAIT_FOR_EV_DISCONNECT,
	CPRO_STATE_PREPARED,
	CPRO_STATE_CONNECTED_ISO15118_ERROR,
	CPRO_STATE_CONNECTED_ISO15118_X1,
	CPRO_STATE_CHECK_RELAYS,
	CPRO_STATE_COUNT
}
