namespace ICUNetwork;

public enum EBoardAssy
{
	BOARDASSEMBLY_UNKNOWN = -1,
	BOARDASSEMBLY_DEFAULT,
	BOARDASSEMBLY_00,
	BOARDASSEMBLY_01,
	BOARDASSEMBLY_02,
	BOARDASSEMBLY_03,
	BOARDASSEMBLY_04,
	BOARDASSEMBLY_05,
	BOARDASSEMBLY_06,
	BOARDASSEMBLY_07,
	BOARDASSEMBLY_08,
	BOARDASSEMBLY_09,
	BOARDASSEMBLY_10,
	BOARDASSEMBLY_11,
	BOARDASSEMBLY_12,
	BOARDASSEMBLY_13,
	BOARDASSEMBLY_14,
	BOARDASSEMBLY_15
}
