namespace ICUNetwork;

public enum EBoardRevision
{
	BOARDREVISION_UNKNOWN = -1,
	BOARDREVISION_DEFAULT,
	BOARDREVISION_A,
	BOARDREVISION_B,
	BOARDREVISION_C,
	BOARDREVISION_D,
	BOARDREVISION_E,
	BOARDREVISION_F,
	BOARDREVISION_G,
	BOARDREVISION_H,
	BOARDREVISION_J,
	BOARDREVISION_K,
	BOARDREVISION_L,
	BOARDREVISION_M,
	BOARDREVISION_N,
	BOARDREVISION_P,
	BOARDREVISION_Q,
	BOARDREVISION_R
}
