namespace ICUNetwork;

public enum EDomainItemType
{
	KEY_BO_AUTHORIZATION = 0,
	KEY_FW_VALIDATION = 1,
	KEY_PROXY_AUTHORIZATION = 2,
	KEY_GETDIAGNOSTICS = 3,
	KEY_FW_ENCRYPTION = 4,
	KEY_DS_ENCRYPTION = 5,
	KEY_PRIVATE_CSR = 6,
	CERT_MANUFACTURER_ROOT = 16,
	CERT_CENTRALSYSTEM_ROOT = 17,
	CERTANDKEY_CLIENTCHAIN = 48,
	PASSWORD_RESET_CODE = 57,
	DOM_UNKNOWN = 255
}
