namespace ICUNetwork;

public enum EMeterTypes
{
	ENERGYMETER_NONE = -1,
	ENERGYMETER_MODBUS_CENTRAL = 0,
	ENERGYMETER_FKN_METER = 2,
	ENERGYMETER_TCPIP_CENTRAL = 3,
	ENERGYMETER_TCPIP_SMART = 4,
	ENERGYMETER_P1 = 5,
	ENERGYMETER_RTU_SMART = 6,
	ENERGYMETER_TIC = 7
}
