namespace ICUNetwork;

public enum EUserInterfaceStates
{
	UI_STATE_UNKNOWN,
	UI_STATE_BOOTING,
	UI_STATE_AVAILABLE,
	UI_STATE_CABLE_CONNECTED,
	UI_STATE_EV_CONNECTED,
	UI_STATE_CABLE_AUTHORISED,
	UI_STATE_AUTHORISED,
	UI_STATE_COMMUNICATING,
	UI_STATE_POWER_OFF_LOW_MAX_CURRENT,
	UI_STATE_POWER_OFF_SUSPENDED,
	UI_STATE_CHARGING,
	UI_STATE_CHARGING_FULL_LOCKED,
	UI_STATE_CHARGING_FULL_UNLOCKED,
	UI_STATE_WAIT_FOR_EV_RECONNECT,
	UI_STATE_TRANSACTION_INFO,
	UI_STATE_CARD_REJECTED,
	UI_STATE_ERROR,
	UI_STATE_PLEASEWAIT,
	UI_STATE_RESERVED,
	UI_STATE_QRCODE,
	UI_STATE_WARNING,
	UI_STATE_WAIT_FOR_RELEASE,
	UI_STATE_PLEASE_REMOVE_CABLE,
	UI_STATE_PLEASEWAIT_EV_COMM,
	UI_STATE_WAIT_FOR_RELEASE_PC,
	UI_STATE_INVALID_CARD
}
